In [1]:
# Quadratic Kappa 

In [2]:
# Lies between -1 and 1. Useful when we are having a ranked target variables/nominal scales.
# For instance if the prediction is 4, but the model predicted it as 3 -- It is ok, but if the model predicted as 1 then 
# it has to be penalized more

In [63]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, cohen_kappa_score,mean_squared_error as mse

In [67]:
print('Case - 1')
actual = [0,4,2,3]
predicted = [1,0,0,0]
print('Accuracy is',accuracy_score(actual,predicted))
print('Quadratic Kappa score is',round(cohen_kappa_score(actual,predicted,weights='quadratic'),2))

print('Case - 2')
actual = [0,4,2,3]
predicted = [1,3,1,2]
print('Accuracy is',accuracy_score(actual,predicted))
print('Quadratic Kappa score is',round(cohen_kappa_score(actual,predicted,weights='quadratic'),2))


Case - 1
Accuracy is 0.0
Quadratic Kappa score is -0.18
Case - 2
Accuracy is 0.0
Quadratic Kappa score is 0.68


Case - 2
Accuracy is 0.0
Quadratic Kappa score is 0.68


1.0

# Calculating Quadratic Kappa score manually

> First, create a multi class confusion matrix O between predicted and actual ratings.
Second, construct a weight matrix w which calculates the weight between the actual and predicted ratings.
Third, calculate value_counts() for each rating in preds and actuals.
Fourth, calculate E, which is the outer product of two value_count vectors
Fifth, normalise the E and O matrix
Caclulate, weighted kappa as per formula

In [2]:
actual = [1,2,1,2,3,4,1,4,0,2]
predicted = [0,0,0,1,1,1,2,2,3,4]

In [36]:
O = confusion_matrix(actual,predicted)
O

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int64)

In [37]:
# Weighted matrix
w = np.zeros((5,5))

In [38]:
w

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
for i in range(5):
    for j in range(5):
        w[i][j] = (float(i-j)**2)/16

In [40]:
w

array([[0.    , 0.0625, 0.25  , 0.5625, 1.    ],
       [0.0625, 0.    , 0.0625, 0.25  , 0.5625],
       [0.25  , 0.0625, 0.    , 0.0625, 0.25  ],
       [0.5625, 0.25  , 0.0625, 0.    , 0.0625],
       [1.    , 0.5625, 0.25  , 0.0625, 0.    ]])

In [41]:
# Create Histogram

In [42]:
act_hist = np.zeros(5)
predict_hist = np.zeros(5)


In [43]:
for i in actual:
    act_hist[i]+=1
act_hist

array([1., 0., 1., 1., 1.])

In [44]:
for j in predicted:
    predict_hist[j]+=1
predict_hist

array([0., 2., 1., 1., 0.])

In [45]:
# Expected Matrix is outer product of act_hist and predict_hist

In [46]:
E = np.outer(act_hist,predict_hist)

In [47]:
E

array([[0., 2., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 1., 1., 0.],
       [0., 2., 1., 1., 0.],
       [0., 2., 1., 1., 0.]])

In [48]:
E.sum()

16.0

In [49]:
O.sum()

4

In [50]:
E = E/E.sum()
E.sum()

1.0

In [51]:
O = O/O.sum()
O.sum()

1.0

In [52]:
E

array([[0.    , 0.125 , 0.0625, 0.0625, 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.125 , 0.0625, 0.0625, 0.    ],
       [0.    , 0.125 , 0.0625, 0.0625, 0.    ],
       [0.    , 0.125 , 0.0625, 0.0625, 0.    ]])

In [53]:
O

array([[0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.  ]])

In [54]:
num = 0
den = 0
for i in range(len(w)):
    for j in range(len(w)):
        num+= w[i][j]*O[i][j]
        den+= w[i][j]*E[i][j]
weighted_kappa = 1 - num/den

In [55]:
weighted_kappa

0.6799999999999999